### ISSUE TITLE
Feature request: Customizable config-file path

### ISSUE THREAD

**Issue by grafluxe** [ariassd/vscode-load-terminals#2]
Firstly, thank you for creating this extension.

Can you add a setting that allows us to specify the config path? That way, we can do something like:

```
// settings.json
{
  ...
  terminalLoader.configPath = ".vscode/terminals.json"
}
```

To be able to save `LoadTerminal.json` in the .vscode directory would be nice. Especially since this extension is specific to vscode -- and not all developers on my team use it (vscode).

**Comment by eagl3s1ght** [comment]
Yes, while I think this extension is a great solution and fills a need-- ./workspaceConfiguration is not a standard path makes things quite cumbersome. Please put it in .vscode instead or even better put it in the actual workspace file that opens when running the command `Workspaces: Open Workspace Configuration File`

**Comment by ariassd** [comment]
Hello, Thank you for your report.

I did an update, I added a simple configuration in .vscode/settings.

I'll dedicate more time for this tool soon

Regards.
