### ISSUE TITLE
Happy day, thanks for the awesome, latest VS Code update borks the loader :(

### ISSUE THREAD

**Issue by ipswitch8** [ariassd/vscode-load-terminals#3]
As team members apply this update to VSCode the loader spins wild, one group only, goes wide until cpu 100% and hangs.

https://code.visualstudio.com/updates/v1_53

Thank you for what you do, -J

**Comment by ariassd** [comment]
Hello, Thank you for your report.

I did an update, please let me know if it's working fine for you.

**Comment by ipswitch8** [comment]
Back to awesome, thank you so much for the fast response, this little critter is handy well done!

It was also good practice as a few more Jr. team members got to say, wait, um, I don't actually know how to run all of this manually, bwhahahaah, good times.
