### ISSUE TITLE
Documentation is incomplete ...

### ISSUE THREAD

**Issue by tohagan** [ariassd/vscode-load-terminals#6]
Features look nice but it would be nice to have the full details of how to configure it.

```json
{
  "version": "1.1.0",
  "groups": [
    {
      ...  /// WHAT GOES HERE?
    }
  ],
  "testEnv": [
      ...  /// WHAT GOES HERE?
  ]
}
```

**Comment by ariassd** [comment]
Hello.

The extension automatically create a sample file like this in the folder you are working on.

```json
{
  "version": "1.2.0",
  "groups": [
    {
      "name": "First group: Sample",
      "description": "First group of terminals and commands",
      "enabled": true,
      "terminals": [
        { "name": "--1g-1c", "path": ".", "cmd": "echo first group first console!", "num": 0 },
        { "name": "--1g-2c", "path": ".", "cmd": "echo first group second console!", "num": 0 }
      ]
    },
    {
      "name": "Second group: Sample",
      "description": "Second group of terminals and commands",
      "enabled": true,
      "terminals": [
        { "name": "--2g-1c", "path": ".", "cmd": "echo Second group first console!", "num": 0 },
        { "name": "--2g-2c", "path": ".", "cmd": "echo Second group second console!", "num": 0 }
      ]
    }
  ]
}

```

I'll update the documentation, thank you for your comments.

**Comment by tohagan** [comment]
I'm using the latest v1.2.1 but I still cannot configure the terminals.  When I run "Load Terminals", it appears to be loading the terminal configuration you've shown above, but my project does not have any such config file in it anywhere (searched all folders including main `.vscode` folder and wworkspace project `.vscode` subfolders).   So it must be getting this config from some global place.  I have a `.vscode/TerminalLoader.json` file but it's ignoring it.  I also have also set  `"terminalLoader.config"` in my Workspace settings  file but it's again .. its ignoring this setting. Restarted VsCode etc with no luck.

"terminalLoader.config": {
    "directory": ".vscode"
  },


I found a copy of ths TerminalLoader.json file under ...
- `C:\Users\<myuser>\.vscode\extensions\ariassd.terminal-loader-1.2.1\workspaceConfiguration`

... and I tried to rename it to disable it and it still opened the 4 terminals configured above so can't be that global copy!

**Comment by tohagan** [comment]
OK ... I just found that it works IF I open a command window and start VS Code in the project folder.  So that suggests that it's not computing the path for the `.vscode` folder correctly.  It should be using `.vscode` folder from the current active workspace or project, which may NOT be the current directory - which it appears to be using.  

The reason that I'm getting the 4 terminals above is it makes a copy of these settings into an initial `LoadTerminal.json` file the first time it starts up but places this file *in the wrong directory* ... which is also the same directory it will later read it from on subsequent start ups.   That's why I originally couldn't find an example of this file in my project!
